<?php

namespace Database\Seeders;

use App\Models\TaxDeduction;
use Illuminate\Database\Seeder;

class TaxDeductionSeeder extends Seeder
{
    public function run(): void
    {
        $deductions = [
            // ═══════════════════════════════════════════════════
            // CATEGORY 1: Above-the-Line Deductions (reduce AGI)
            // ═══════════════════════════════════════════════════
            [
                'slug' => 'student-loan-interest',
                'name' => 'Student Loan Interest',
                'description' => 'Deduct interest paid on qualified student loans, up to $2,500 per year.',
                'category' => 'above_the_line',
                'subcategory' => 'Education',
                'max_amount' => 2500,
                'max_amount_mfj' => 2500,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => '21',
                'eligibility_rules' => json_encode(['income_limit' => 85000, 'income_limit_mfj' => 170000]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['navient', 'fedloan', 'nelnet', 'great lakes', 'student loan', 'sallie mae', 'mohela', 'aidvantage']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'You can deduct up to $2,500 in student loan interest if your MAGI is under $85,000 ($170,000 MFJ).',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'hsa-contributions',
                'name' => 'HSA Contributions',
                'description' => 'Contributions to a Health Savings Account are tax-deductible.',
                'category' => 'above_the_line',
                'subcategory' => 'Health',
                'max_amount' => 4400,
                'max_amount_mfj' => 8750,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Form 8889',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['hsa', 'health savings']),
                'question_text' => 'Do you have a high-deductible health plan with an HSA?',
                'question_options' => null,
                'help_text' => 'Must have an HSA-eligible high-deductible health plan. Limits: $4,400 individual / $8,750 family (2026).',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'traditional-ira-contributions',
                'name' => 'Traditional IRA Contributions',
                'description' => 'Contributions to a traditional IRA may be fully or partially deductible.',
                'category' => 'above_the_line',
                'subcategory' => 'Retirement',
                'max_amount' => 7500,
                'max_amount_mfj' => 15000,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => '20',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['ira contribution', 'traditional ira', 'vanguard ira', 'fidelity ira', 'schwab ira']),
                'question_text' => 'Did you contribute to a traditional IRA this year?',
                'question_options' => null,
                'help_text' => 'Deduction may be limited if you or your spouse has a workplace retirement plan. Max: $7,500 ($8,600 if 50+).',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'self-employment-tax',
                'name' => 'Self-Employment Tax (50%)',
                'description' => 'Deduct 50% of your self-employment tax from gross income.',
                'category' => 'above_the_line',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule SE',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Are you self-employed, a freelancer, or an independent contractor?',
                'question_options' => null,
                'help_text' => 'If you pay self-employment tax, you can deduct half of it from your gross income.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'self-employed-health-insurance',
                'name' => 'Self-Employed Health Insurance',
                'description' => 'Self-employed individuals can deduct 100% of health insurance premiums.',
                'category' => 'above_the_line',
                'subcategory' => 'Health',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => '17',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['health insurance', 'medical insurance', 'dental insurance', 'vision insurance']),
                'question_text' => 'Do you pay for your own health insurance as a self-employed individual?',
                'question_options' => null,
                'help_text' => 'You can deduct premiums for medical, dental, and long-term care insurance for yourself, spouse, and dependents.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'educator-expenses',
                'name' => 'Educator Expenses',
                'description' => 'K-12 educators can deduct up to $300 for unreimbursed classroom expenses.',
                'category' => 'above_the_line',
                'subcategory' => 'Education',
                'max_amount' => 300,
                'max_amount_mfj' => 600,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => '11',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Are you a K-12 teacher, instructor, counselor, principal, or aide?',
                'question_options' => null,
                'help_text' => 'Must work at least 900 hours in a school year. $300 per educator ($600 if both spouses are educators).',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'military-moving-expenses',
                'name' => 'Military Moving Expenses',
                'description' => 'Active-duty military can deduct unreimbursed moving expenses for PCS orders.',
                'category' => 'above_the_line',
                'subcategory' => 'Military',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Form 3903',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Are you active-duty military with permanent change of station (PCS) orders?',
                'question_options' => null,
                'help_text' => 'Only active-duty military members with PCS orders can deduct moving expenses.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'alimony-payments',
                'name' => 'Alimony Payments',
                'description' => 'Alimony paid under pre-2019 divorce agreements is deductible.',
                'category' => 'above_the_line',
                'subcategory' => 'Personal',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => '19a',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Do you pay alimony under a divorce agreement executed before 2019?',
                'question_options' => null,
                'help_text' => 'Only applies to divorce or separation agreements executed before January 1, 2019.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'early-withdrawal-penalty',
                'name' => 'Penalty on Early Withdrawal of Savings',
                'description' => 'Deduct penalties charged by a financial institution for early withdrawal.',
                'category' => 'above_the_line',
                'subcategory' => 'Financial',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => '18',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['early withdrawal penalty', 'penalty interest', 'cd penalty']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Banks report this on Form 1099-INT or 1099-OID.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'slug' => 'archer-msa-contributions',
                'name' => 'Archer MSA Contributions',
                'description' => 'Contributions to an Archer Medical Savings Account are deductible.',
                'category' => 'above_the_line',
                'subcategory' => 'Health',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Form 8853',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you contribute to an Archer MSA?',
                'question_options' => null,
                'help_text' => 'Available to self-employed and employees of small employers with high-deductible plans.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],

            // ═══════════════════════════════════════════════════
            // CATEGORY 2: Itemized Deductions (Schedule A)
            // ═══════════════════════════════════════════════════
            [
                'slug' => 'medical-dental-expenses',
                'name' => 'Medical & Dental Expenses',
                'description' => 'Deduct unreimbursed medical and dental expenses exceeding 7.5% of AGI.',
                'category' => 'itemized',
                'subcategory' => 'Medical',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '1-4',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['doctor', 'dentist', 'dental', 'pharmacy', 'cvs pharmacy', 'walgreens pharmacy', 'hospital', 'medical', 'urgent care', 'optometrist', 'orthodont', 'chiropract', 'physical therapy', 'mental health', 'therapist', 'counseling', 'dermatolog', 'pediatric', 'obgyn']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Only the amount exceeding 7.5% of your AGI is deductible. Includes doctors, dentists, prescriptions, medical equipment.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'salt-deduction',
                'name' => 'State & Local Taxes (SALT)',
                'description' => 'Deduct state and local income, sales, and property taxes up to $40,000.',
                'category' => 'itemized',
                'subcategory' => 'Taxes',
                'max_amount' => 40000,
                'max_amount_mfj' => 40000,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '5-7',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['property tax', 'state tax', 'county tax']),
                'question_text' => 'Do you pay state income taxes, sales taxes, or property taxes?',
                'question_options' => null,
                'help_text' => 'SALT cap raised to $40,000 for 2025+. Includes state/local income tax, sales tax, and real estate tax.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'mortgage-interest',
                'name' => 'Mortgage Interest',
                'description' => 'Deduct interest paid on mortgage debt up to $750,000.',
                'category' => 'itemized',
                'subcategory' => 'Home',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '8a-8c',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['mortgage', 'home loan']),
                'question_text' => 'Do you have a mortgage on your primary or second home?',
                'question_options' => null,
                'help_text' => 'Deductible on first $750,000 of mortgage debt. Your lender sends Form 1098.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'charitable-contributions',
                'name' => 'Charitable Contributions',
                'description' => 'Deduct donations to qualified 501(c)(3) organizations.',
                'category' => 'itemized',
                'subcategory' => 'Giving',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '11-14',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['goodwill', 'salvation army', 'red cross', 'united way', 'habitat for humanity', 'donors choose', 'charity', 'donation', 'tithe', 'church', 'synagogue', 'mosque', 'temple', 'non-profit', 'nonprofit']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Cash donations limited to 60% of AGI. Keep receipts for donations over $250.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'gambling-losses',
                'name' => 'Gambling Losses',
                'description' => 'Deduct gambling losses up to the amount of gambling winnings.',
                'category' => 'itemized',
                'subcategory' => 'Personal',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '16',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you have gambling winnings this year?',
                'question_options' => null,
                'help_text' => 'You can deduct gambling losses up to 90% of losses (2026+) but only if you itemize and had gambling winnings.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'casualty-theft-losses',
                'name' => 'Casualty & Theft Losses',
                'description' => 'Deduct unreimbursed losses from a federally declared disaster.',
                'category' => 'itemized',
                'subcategory' => 'Personal',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Form 4684',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you suffer losses from a federally declared disaster this year?',
                'question_options' => null,
                'help_text' => 'Must be from a presidentially declared disaster. $100 floor per event + 10% AGI threshold.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'investment-interest-expense',
                'name' => 'Investment Interest Expense',
                'description' => 'Deduct interest paid on money borrowed to make taxable investments.',
                'category' => 'itemized',
                'subcategory' => 'Financial',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Form 4952',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you pay interest on money borrowed to make investments?',
                'question_options' => null,
                'help_text' => 'Limited to your net investment income. Margin interest from brokerage accounts qualifies.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],

            // ═══════════════════════════════════════════════════
            // CATEGORY 3: Schedule C (Self-Employed Business)
            // ═══════════════════════════════════════════════════
            [
                'slug' => 'home-office',
                'name' => 'Home Office Deduction',
                'description' => 'Deduct expenses for the business use of your home.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => 1500,
                'max_amount_mfj' => 1500,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Form 8829',
                'irs_line' => '30',
                'eligibility_rules' => json_encode(['requires_self_employed' => true, 'requires_home_office' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Do you use part of your home exclusively for business?',
                'question_options' => null,
                'help_text' => 'Simplified method: $5/sq ft, max 300 sq ft ($1,500). Or calculate actual expenses (mortgage, utilities, insurance).',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'vehicle-expenses',
                'name' => 'Vehicle / Mileage Expenses',
                'description' => 'Deduct business use of your vehicle at the standard mileage rate or actual expenses.',
                'category' => 'schedule_c',
                'subcategory' => 'Transportation',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '9',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['gas station', 'shell', 'chevron', 'exxon', 'bp', 'wawa', 'sheetz', 'parking', 'toll', 'ez pass', 'fastrak', 'sunoco', 'speedway']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Standard mileage rate: $0.725/mile (2026). Or actual expenses (gas, insurance, repairs, depreciation).',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'business-meals',
                'name' => 'Business Meals (50%)',
                'description' => 'Deduct 50% of meals with clients, prospects, or while traveling for business.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '24b',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['restaurant', 'grubhub', 'doordash', 'uber eats', 'postmates', 'caviar', 'seamless']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => '50% deductible. Must be directly related to business. Keep receipts with who, where, why.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'advertising-marketing',
                'name' => 'Advertising & Marketing',
                'description' => 'Business advertising and marketing expenses are fully deductible.',
                'category' => 'schedule_c',
                'subcategory' => 'Marketing',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '8',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['facebook ads', 'google ads', 'meta ads', 'linkedin ads', 'mailchimp', 'constant contact', 'canva', 'vistaprint', 'hootsuite', 'buffer']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Includes online ads, print ads, business cards, signage, website costs.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'office-supplies',
                'name' => 'Office Supplies',
                'description' => 'Deduct supplies used in your business operations.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '22',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['staples', 'office depot', 'office max', 'amazon business']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Paper, pens, printer ink, postage, and other office consumables.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'software-saas',
                'name' => 'Software & SaaS Subscriptions',
                'description' => 'Business software subscriptions and cloud services are deductible.',
                'category' => 'schedule_c',
                'subcategory' => 'Technology',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['adobe', 'slack', 'zoom', 'microsoft 365', 'google workspace', 'dropbox', 'notion', 'figma', 'github', 'aws', 'heroku', 'digitalocean', 'vercel', 'netlify', 'quickbooks', 'freshbooks', 'xero']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Includes cloud services, design tools, accounting software, project management tools.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'professional-services',
                'name' => 'Professional Services',
                'description' => 'Legal, accounting, and consulting fees for business are deductible.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '17',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['legal', 'attorney', 'lawyer', 'accounting', 'cpa', 'bookkeeper', 'consultant', 'legalzoom', 'rocket lawyer']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Includes tax preparation, legal advice, consulting, and accounting services for business.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'business-insurance',
                'name' => 'Business Insurance',
                'description' => 'Premiums for business-related insurance are deductible.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '15',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['business insurance', 'liability insurance', 'e&o insurance', 'professional liability', 'general liability']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'General liability, professional liability (E&O), business property insurance.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'business-travel',
                'name' => 'Business Travel',
                'description' => 'Travel expenses away from home for business purposes are deductible.',
                'category' => 'schedule_c',
                'subcategory' => 'Travel',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '24a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['airline', 'delta', 'united', 'american airlines', 'southwest', 'hotel', 'marriott', 'hilton', 'hyatt', 'airbnb', 'vrbo', 'hertz', 'enterprise', 'avis']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Includes flights, hotels, rental cars, taxis, and 50% of meals while traveling.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'slug' => 'continuing-education',
                'name' => 'Continuing Education',
                'description' => 'Education that improves existing business skills is deductible.',
                'category' => 'schedule_c',
                'subcategory' => 'Education',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['udemy', 'coursera', 'skillshare', 'linkedin learning', 'masterclass', 'seminar', 'workshop', 'conference', 'pluralsight']),
                'question_text' => 'Did you take courses or attend conferences to improve your business skills?',
                'question_options' => null,
                'help_text' => 'Must improve or maintain skills for your current business. Cannot qualify you for a new trade.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'slug' => 'cell-phone',
                'name' => 'Cell Phone (Business Use)',
                'description' => 'Deduct the business-use percentage of your cell phone plan.',
                'category' => 'schedule_c',
                'subcategory' => 'Utilities',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '25',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['verizon', 'at&t', 't-mobile', 'sprint', 'mint mobile', 'google fi', 'visible', 'cricket']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Deduct the business-use percentage of your monthly plan. Track business vs personal calls.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'slug' => 'internet-service',
                'name' => 'Internet Service (Business Use)',
                'description' => 'Deduct the business-use percentage of your internet service.',
                'category' => 'schedule_c',
                'subcategory' => 'Utilities',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '25',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['comcast', 'xfinity', 'spectrum', 'cox', 'att internet', 'verizon fios', 'google fiber', 'starlink']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Deduct the business-use percentage. If you work from home full-time, this could be 50-100%.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'slug' => 'business-licenses',
                'name' => 'Business Licenses & Permits',
                'description' => 'Fees for business licenses and permits are deductible.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['business license', 'llc filing', 'permit fee', 'secretary of state']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Annual business license renewals, professional certifications, and permit fees.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'slug' => 'contract-labor',
                'name' => 'Contract Labor',
                'description' => 'Payments to contractors and freelancers are deductible.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '11',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you pay any contractors or freelancers (1099 payments)?',
                'question_options' => null,
                'help_text' => 'You must issue Form 1099-NEC for payments of $600+ to non-employees.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'slug' => 'equipment-depreciation',
                'name' => 'Equipment & Depreciation (Section 179)',
                'description' => 'Deduct the full cost of qualifying business equipment in the year of purchase.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => 1250000,
                'max_amount_mfj' => 1250000,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Form 4562',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you purchase business equipment costing more than $2,500?',
                'question_options' => null,
                'help_text' => 'Section 179 lets you expense the full cost immediately rather than depreciating over years.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'slug' => 'business-rent',
                'name' => 'Business Rent',
                'description' => 'Rent for business property, office space, or equipment.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '20b',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['office rent', 'coworking', 'wework', 'regus']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Rent for office space, coworking memberships, equipment rental.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'slug' => 'business-repairs',
                'name' => 'Business Repairs & Maintenance',
                'description' => 'Repairs to business property and equipment.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '21',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you pay for repairs or maintenance of business property or equipment?',
                'question_options' => null,
                'help_text' => 'Repairs that keep property in working condition are currently deductible.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'slug' => 'shipping-postage',
                'name' => 'Shipping & Postage',
                'description' => 'Business shipping and postage expenses.',
                'category' => 'schedule_c',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['usps', 'fedex', 'ups', 'dhl', 'stamps.com', 'pirate ship', 'shipstation']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Postage, shipping supplies, courier services for business.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'slug' => 'bank-fees',
                'name' => 'Business Bank & Payment Processing Fees',
                'description' => 'Bank fees, merchant processing fees, and payment platform fees for business.',
                'category' => 'schedule_c',
                'subcategory' => 'Financial',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['stripe fee', 'paypal fee', 'square fee', 'merchant fee', 'processing fee', 'bank fee']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Credit card processing fees, PayPal/Stripe fees, monthly bank account fees for business.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 19,
            ],

            // ═══════════════════════════════════════════════════
            // CATEGORY 4: Tax Credits
            // ═══════════════════════════════════════════════════
            [
                'slug' => 'child-tax-credit',
                'name' => 'Child Tax Credit',
                'description' => 'Tax credit for each qualifying child under age 17.',
                'category' => 'credit',
                'subcategory' => 'Family',
                'max_amount' => 2200,
                'max_amount_mfj' => 2200,
                'is_credit' => true,
                'is_refundable' => true,
                'irs_form' => 'Schedule 8812',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Do you have children under age 17?',
                'question_options' => null,
                'help_text' => '$2,200 per qualifying child (2025). Partially refundable. Income phase-out: $200k/$400k MFJ.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'child-dependent-care-credit',
                'name' => 'Child & Dependent Care Credit',
                'description' => 'Credit for childcare or dependent care expenses that allow you to work.',
                'category' => 'credit',
                'subcategory' => 'Family',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 2441',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['daycare', 'childcare', 'bright horizons', 'kindercare', 'montessori', 'preschool', 'after school', 'nanny']),
                'question_text' => 'Did you pay for childcare or dependent care so you could work?',
                'question_options' => null,
                'help_text' => 'Up to 50% of expenses (2026+). Max $3,000 for one dependent, $6,000 for two or more.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'earned-income-credit',
                'name' => 'Earned Income Tax Credit (EITC)',
                'description' => 'Refundable credit for low-to-moderate income workers.',
                'category' => 'credit',
                'subcategory' => 'Income',
                'max_amount' => 8231,
                'max_amount_mfj' => 8231,
                'is_credit' => true,
                'is_refundable' => true,
                'irs_form' => 'Schedule EIC',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['income_limit' => 66819]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Is your household income under $66,819?',
                'question_options' => null,
                'help_text' => 'Up to $8,231 for 3+ qualifying children. Must have earned income. Investment income must be under $11,600.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'american-opportunity-credit',
                'name' => 'American Opportunity Tax Credit',
                'description' => 'Credit for first 4 years of post-secondary education.',
                'category' => 'credit',
                'subcategory' => 'Education',
                'max_amount' => 2500,
                'max_amount_mfj' => 2500,
                'is_credit' => true,
                'is_refundable' => true,
                'irs_form' => 'Form 8863',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['income_limit' => 90000, 'income_limit_mfj' => 180000]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['tuition', 'university', 'college', 'student account']),
                'question_text' => 'Are you or a dependent in the first 4 years of college?',
                'question_options' => null,
                'help_text' => '$2,500 per student. 40% refundable ($1,000). MAGI limit: $90k/$180k MFJ.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'lifetime-learning-credit',
                'name' => 'Lifetime Learning Credit',
                'description' => 'Credit for any post-secondary education or skill improvement courses.',
                'category' => 'credit',
                'subcategory' => 'Education',
                'max_amount' => 2000,
                'max_amount_mfj' => 2000,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 8863',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['income_limit' => 90000, 'income_limit_mfj' => 180000]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you pay for post-secondary education or skill-improvement courses?',
                'question_options' => null,
                'help_text' => '20% of first $10,000 in tuition. No limit on number of years. Cannot combine with AOTC for same student.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'adoption-credit',
                'name' => 'Adoption Credit',
                'description' => 'Credit for qualified adoption expenses.',
                'category' => 'credit',
                'subcategory' => 'Family',
                'max_amount' => 17670,
                'max_amount_mfj' => 17670,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 8839',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you adopt a child this year?',
                'question_options' => null,
                'help_text' => 'Up to $17,670 per child. Includes attorney fees, court costs, travel. Income phase-out: $252,150-$292,150.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'savers-credit',
                'name' => "Saver's Credit (Retirement Savings)",
                'description' => 'Credit for low-to-moderate income retirement savers.',
                'category' => 'credit',
                'subcategory' => 'Retirement',
                'max_amount' => 1000,
                'max_amount_mfj' => 2000,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 8880',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['income_limit' => 38250, 'income_limit_mfj' => 76500]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you contribute to a retirement account and is your income under $38,250 ($76,500 MFJ)?',
                'question_options' => null,
                'help_text' => '10-50% of first $2,000 contributed to IRA/401(k)/403(b). Must be 18+, not a student.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'energy-efficient-home-credit',
                'name' => 'Energy Efficient Home Improvement Credit',
                'description' => 'Credit for energy-efficient home improvements.',
                'category' => 'credit',
                'subcategory' => 'Home',
                'max_amount' => 3200,
                'max_amount_mfj' => 3200,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 5695',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['home depot', 'lowes', 'hvac', 'insulation', 'energy star', 'solar']),
                'question_text' => 'Did you make energy-efficient improvements to your home?',
                'question_options' => null,
                'help_text' => '30% of cost for qualifying improvements. $1,200 annual limit for most items, $2,000 for heat pumps.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'residential-clean-energy-credit',
                'name' => 'Residential Clean Energy Credit',
                'description' => 'Credit for installing solar, wind, or geothermal systems.',
                'category' => 'credit',
                'subcategory' => 'Home',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 5695',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you install solar panels, wind energy, or geothermal systems at your home?',
                'question_options' => null,
                'help_text' => '30% of cost through 2032. No maximum. Includes solar electric, solar water heating, battery storage.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'slug' => 'ev-credit-new',
                'name' => 'Electric Vehicle Credit (New)',
                'description' => 'Credit for purchasing a new qualifying electric vehicle.',
                'category' => 'credit',
                'subcategory' => 'Vehicle',
                'max_amount' => 7500,
                'max_amount_mfj' => 7500,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 8936',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['income_limit' => 150000, 'income_limit_mfj' => 300000]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you purchase a new electric vehicle this year?',
                'question_options' => null,
                'help_text' => 'Up to $7,500. Vehicle must be assembled in North America. MAGI limit: $150k/$300k MFJ.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'slug' => 'ev-credit-used',
                'name' => 'Electric Vehicle Credit (Used)',
                'description' => 'Credit for purchasing a qualifying used electric vehicle.',
                'category' => 'credit',
                'subcategory' => 'Vehicle',
                'max_amount' => 4000,
                'max_amount_mfj' => 4000,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 8936',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['income_limit' => 75000, 'income_limit_mfj' => 150000]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you purchase a used electric vehicle this year?',
                'question_options' => null,
                'help_text' => 'Up to $4,000 or 30% of sale price. Vehicle must be at least 2 years old. MAGI limit: $75k/$150k MFJ.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'slug' => 'premium-tax-credit',
                'name' => 'Premium Tax Credit',
                'description' => 'Credit for health insurance purchased through the ACA marketplace.',
                'category' => 'credit',
                'subcategory' => 'Health',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => true,
                'is_refundable' => true,
                'irs_form' => 'Form 8962',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Do you have health insurance through the ACA marketplace (Healthcare.gov)?',
                'question_options' => null,
                'help_text' => 'Reduces premiums for marketplace insurance. Amount varies by income and household size.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'slug' => 'elderly-disabled-credit',
                'name' => 'Credit for the Elderly or Disabled',
                'description' => 'Credit for taxpayers age 65+ or permanently disabled.',
                'category' => 'credit',
                'subcategory' => 'Personal',
                'max_amount' => 1125,
                'max_amount_mfj' => 1125,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Schedule R',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Are you age 65 or older, or permanently and totally disabled?',
                'question_options' => null,
                'help_text' => 'Small credit for low-income seniors and disabled individuals.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'slug' => 'foreign-tax-credit',
                'name' => 'Foreign Tax Credit',
                'description' => 'Credit for taxes paid to foreign governments on foreign income.',
                'category' => 'credit',
                'subcategory' => 'International',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => true,
                'is_refundable' => false,
                'irs_form' => 'Form 1116',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you pay income taxes to a foreign country?',
                'question_options' => null,
                'help_text' => 'Prevents double taxation on foreign income. Can be claimed as credit or deduction.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 14,
            ],

            // ═══════════════════════════════════════════════════
            // CATEGORY 5: New for 2026 (One Big Beautiful Bill)
            // ═══════════════════════════════════════════════════
            [
                'slug' => 'senior-additional-deduction',
                'name' => 'Senior Additional Deduction',
                'description' => 'Additional standard deduction for taxpayers age 65+.',
                'category' => 'new_2026',
                'subcategory' => 'Personal',
                'max_amount' => 6000,
                'max_amount_mfj' => 12000,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Are you age 65 or older?',
                'question_options' => null,
                'help_text' => 'New for 2026: Additional $6,000 deduction ($12,000 MFJ if both 65+) under the One Big Beautiful Bill.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'tip-income-deduction',
                'name' => 'Tip Income Deduction',
                'description' => 'New deduction for tip income received by tipped workers.',
                'category' => 'new_2026',
                'subcategory' => 'Income',
                'max_amount' => 25000,
                'max_amount_mfj' => 25000,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Do you receive tip income as part of your compensation?',
                'question_options' => null,
                'help_text' => 'New for 2026: Deduct up to $25,000 in tip income from federal taxes.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'overtime-deduction',
                'name' => 'Overtime Pay Deduction',
                'description' => 'New deduction for overtime pay earned by W2 employees.',
                'category' => 'new_2026',
                'subcategory' => 'Income',
                'max_amount' => 12500,
                'max_amount_mfj' => 25000,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['employment_type' => ['w2', 'employed']]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you earn overtime pay this year?',
                'question_options' => null,
                'help_text' => 'New for 2026: Deduct up to $12,500 ($25,000 MFJ) of overtime wages from federal taxes.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'auto-loan-interest',
                'name' => 'Auto Loan Interest Deduction',
                'description' => 'New deduction for interest paid on auto loans for American-made vehicles.',
                'category' => 'new_2026',
                'subcategory' => 'Vehicle',
                'max_amount' => 10000,
                'max_amount_mfj' => 10000,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['auto loan', 'car payment', 'car loan', 'auto finance']),
                'question_text' => 'Do you have a loan on an American-made vehicle?',
                'question_options' => null,
                'help_text' => 'New for 2026: Deduct up to $10,000 in auto loan interest on vehicles assembled in the US.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'charitable-standard-deduction',
                'name' => 'Charitable Deduction (Standard Deduction Filers)',
                'description' => 'New above-the-line deduction for charitable contributions even with standard deduction.',
                'category' => 'new_2026',
                'subcategory' => 'Giving',
                'max_amount' => 1000,
                'max_amount_mfj' => 2000,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'both',
                'transaction_keywords' => json_encode(['goodwill', 'salvation army', 'red cross', 'united way', 'charity', 'donation', 'tithe', 'church']),
                'question_text' => 'Did you make charitable donations even if taking the standard deduction?',
                'question_options' => null,
                'help_text' => 'New for 2026: Deduct up to $1,000 ($2,000 MFJ) in charitable gifts even without itemizing.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'newborn-bonus-credit',
                'name' => 'Trump Accounts / Baby Bonus',
                'description' => 'New $1,000 savings account contribution for newborns.',
                'category' => 'new_2026',
                'subcategory' => 'Family',
                'max_amount' => 1000,
                'max_amount_mfj' => 1000,
                'is_credit' => true,
                'is_refundable' => true,
                'irs_form' => '1040',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you have or adopt a child this year?',
                'question_options' => null,
                'help_text' => 'New for 2026: $1,000 government-funded savings account for newborns and newly adopted children.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],

            // ═══════════════════════════════════════════════════
            // CATEGORY 6: Lesser-Known / Unusual
            // ═══════════════════════════════════════════════════
            [
                'slug' => 'guard-dog',
                'name' => 'Guard Dog Expenses',
                'description' => 'Expenses for a guard dog used exclusively for business security.',
                'category' => 'lesser_known',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Do you use a guard dog for business security purposes?',
                'question_options' => null,
                'help_text' => 'Food, vet care, and training for a dog used primarily to guard business property.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'work-clothes-uniforms',
                'name' => 'Work Clothes & Uniforms',
                'description' => 'Deduct required uniforms that cannot be worn as everyday clothing.',
                'category' => 'lesser_known',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Do you purchase required work uniforms that cannot be worn off-duty?',
                'question_options' => null,
                'help_text' => 'Must be required by employer and not suitable for everyday wear. Includes safety equipment.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'job-search-expenses',
                'name' => 'Job Search Expenses',
                'description' => 'Expenses related to searching for a new job in your current field.',
                'category' => 'lesser_known',
                'subcategory' => 'Career',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['indeed', 'linkedin premium', 'resume', 'career coaching']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Self-employed: resume printing, job placement, travel for interviews in your current field.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'safe-deposit-box',
                'name' => 'Safe Deposit Box',
                'description' => 'Rental fee for a safe deposit box used to store investment documents.',
                'category' => 'lesser_known',
                'subcategory' => 'Financial',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['safe deposit', 'safety deposit']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Deductible if used to store investment-related documents or tax records.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'slug' => 'tax-prep-fees',
                'name' => 'Tax Preparation Fees',
                'description' => 'Cost of tax software and professional tax preparation.',
                'category' => 'lesser_known',
                'subcategory' => 'Financial',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule C',
                'irs_line' => '27a',
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['turbotax', 'h&r block', 'tax prep', 'intuit', 'taxact', 'jackson hewitt', 'taxslayer', 'freetaxusa']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'Self-employed can deduct the business portion of tax preparation fees.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'slug' => 'foster-care-expenses',
                'name' => 'Foster Care Expenses',
                'description' => 'Unreimbursed expenses for providing foster care.',
                'category' => 'lesser_known',
                'subcategory' => 'Family',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '11',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Are you a licensed foster parent?',
                'question_options' => null,
                'help_text' => 'Unreimbursed out-of-pocket expenses for foster care may be deductible as charitable contributions.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'organ-donation-expenses',
                'name' => 'Organ Donation Expenses',
                'description' => 'Travel and lodging expenses related to organ donation.',
                'category' => 'lesser_known',
                'subcategory' => 'Medical',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '1',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you donate an organ and incur related travel or lodging expenses?',
                'question_options' => null,
                'help_text' => 'Travel, meals, and lodging for organ donation count as medical expenses.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'breast-pump-supplies',
                'name' => 'Breast Pump & Supplies',
                'description' => 'Breast pumps and lactation supplies are a qualified medical expense.',
                'category' => 'lesser_known',
                'subcategory' => 'Medical',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '1',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'transaction_scan',
                'transaction_keywords' => json_encode(['breast pump', 'medela', 'spectra', 'elvie', 'willow pump', 'lactation']),
                'question_text' => null,
                'question_options' => null,
                'help_text' => 'IRS considers breast pumps and supplies a qualified medical expense. HSA/FSA eligible.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'slug' => 'swimming-pool-medical',
                'name' => 'Swimming Pool (Medical)',
                'description' => 'A swimming pool prescribed by a doctor for medical treatment may be deductible.',
                'category' => 'lesser_known',
                'subcategory' => 'Medical',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '1',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Was a swimming pool prescribed by a doctor for medical treatment (e.g., arthritis, physical therapy)?',
                'question_options' => null,
                'help_text' => 'Must be prescribed by a doctor for a specific medical condition. Only the cost exceeding home value increase.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'slug' => 'specialized-disability-equipment',
                'name' => 'Specialized Disability Equipment',
                'description' => 'Equipment and modifications for a disability.',
                'category' => 'lesser_known',
                'subcategory' => 'Medical',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule A',
                'irs_line' => '1',
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you purchase specialized equipment or make home modifications for a disability?',
                'question_options' => null,
                'help_text' => 'Wheelchair ramps, hand controls for vehicles, hearing aids, and other accessibility equipment.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'slug' => 'hobby-income-offset',
                'name' => 'Hobby Loss Offset',
                'description' => 'Expenses from hobbies that generate income can offset that income.',
                'category' => 'lesser_known',
                'subcategory' => 'Personal',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Schedule 1',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Do you have a hobby that generates income (Etsy, crafts, photography)?',
                'question_options' => null,
                'help_text' => 'Hobby expenses can offset hobby income but cannot create a loss. Report income on Schedule 1.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'slug' => 'moving-expense-first-job',
                'name' => 'Moving Expenses (Self-Employed)',
                'description' => 'Self-employed individuals may deduct certain moving expenses.',
                'category' => 'lesser_known',
                'subcategory' => 'Business',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => 'Form 3903',
                'irs_line' => null,
                'eligibility_rules' => json_encode(['requires_self_employed' => true]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you move this year for a new job or business location (at least 50 miles)?',
                'question_options' => null,
                'help_text' => 'New workplace must be at least 50 miles farther from old home. Must work full-time for 39 weeks.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'slug' => 'student-loan-forgiveness',
                'name' => 'Student Loan Forgiveness (State Tax)',
                'description' => 'Some states exclude forgiven student loan debt from taxable income.',
                'category' => 'lesser_known',
                'subcategory' => 'Education',
                'max_amount' => null,
                'max_amount_mfj' => null,
                'is_credit' => false,
                'is_refundable' => false,
                'irs_form' => '1040',
                'irs_line' => null,
                'eligibility_rules' => json_encode([]),
                'detection_method' => 'profile_question',
                'transaction_keywords' => null,
                'question_text' => 'Did you have any student loan debt forgiven this year?',
                'question_options' => null,
                'help_text' => 'Federally forgiven student loans are not taxable through 2025. Check state rules for 2026.',
                'irs_url' => null,
                'is_active' => true,
                'sort_order' => 13,
            ],
        ];

        TaxDeduction::upsert($deductions, ['slug'], [
            'name', 'description', 'category', 'subcategory',
            'max_amount', 'max_amount_mfj', 'is_credit', 'is_refundable',
            'irs_form', 'irs_line', 'eligibility_rules', 'detection_method',
            'transaction_keywords', 'question_text', 'question_options',
            'help_text', 'irs_url', 'is_active', 'sort_order',
        ]);
    }
}
