<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #333; line-height: 1.6; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #1a5276; color: white; padding: 24px 30px; border-radius: 8px 8px 0 0; }
        .header h1 { margin: 0; font-size: 22px; }
        .header p { margin: 4px 0 0; opacity: 0.8; font-size: 13px; }
        .content { background: #ffffff; border: 1px solid #e0e0e0; border-top: none; padding: 30px; border-radius: 0 0 8px 8px; }
        .stat-row { display: flex; gap: 16px; margin: 20px 0; }
        .stat-box { flex: 1; background: #f5f7fa; border-radius: 8px; padding: 16px; text-align: center; }
        .stat-box .number { font-size: 24px; font-weight: 700; color: #2e7d32; }
        .stat-box .label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
        .files { background: #f5f7fa; border-radius: 8px; padding: 16px; margin: 20px 0; }
        .files h3 { margin: 0 0 10px; font-size: 13px; color: #1a5276; }
        .file-item { display: flex; align-items: center; gap: 8px; padding: 6px 0; font-size: 13px; }
        .file-icon { width: 28px; height: 28px; border-radius: 6px; display: flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 700; color: white; }
        .disclaimer { font-size: 11px; color: #999; margin-top: 24px; padding-top: 16px; border-top: 1px solid #eee; }
        table.summary { width: 100%; border-collapse: collapse; margin: 16px 0; }
        table.summary td { padding: 8px 12px; font-size: 13px; border-bottom: 1px solid #eee; }
        table.summary td:last-child { text-align: right; font-weight: 600; }
        .highlight { background: #e8f5e9; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Tax Deduction Report — {{ $year }}</h1>
        <p>Prepared for {{ $user->name }} via {{ config('app.name') }} AI Expense Tracker</p>
    </div>

    <div class="content">
        <p>Hello,</p>
        <p>
            {{ $user->name }} has shared their {{ $year }} tax deduction report with you.
            This package was generated by {{ config('app.name') }} and includes AI-categorized expense data
            from {{ $summary['total_line_items'] }} transactions across their linked financial accounts.
        </p>

        <!-- Summary Stats -->
        <table class="summary">
            <tr>
                <td>Total Deductible Expenses</td>
                <td>${{ number_format($summary['grand_total_deductible'], 2) }}</td>
            </tr>
            <tr>
                <td>Bank Transactions</td>
                <td>${{ number_format($summary['total_deductible_transactions'], 2) }}</td>
            </tr>
            <tr>
                <td>Itemized Email Receipts</td>
                <td>${{ number_format($summary['total_deductible_items'], 2) }}</td>
            </tr>
            <tr class="highlight">
                <td><strong>Estimated Tax Savings ({{ $summary['effective_rate_used'] * 100 }}%)</strong></td>
                <td><strong style="color: #2e7d32;">${{ number_format($summary['estimated_tax_savings'], 2) }}</strong></td>
            </tr>
        </table>

        <!-- Attached Files -->
        <div class="files">
            <h3>📎 Attached Files</h3>
            <div class="file-item">
                <span class="file-icon" style="background: #1565c0;">XLS</span>
                <span><strong>LedgerIQ_Tax_{{ $year }}.xlsx</strong> — Full workbook with 5 tabs: Summary, Schedule C Mapping, Categories, Transaction Detail, Subscriptions</span>
            </div>
            <div class="file-item">
                <span class="file-icon" style="background: #c62828;">PDF</span>
                <span><strong>LedgerIQ_Tax_Summary_{{ $year }}.pdf</strong> — Printable cover sheet with Schedule C mapping and category totals</span>
            </div>
            <div class="file-item">
                <span class="file-icon" style="background: #2e7d32;">CSV</span>
                <span><strong>LedgerIQ_Transactions_{{ $year }}.csv</strong> — Raw transaction data for import into tax software</span>
            </div>
        </div>

        <p style="font-size: 13px; color: #666;">
            The Excel workbook is the most comprehensive file. The <strong>Schedule C Mapping</strong> tab
            maps expenses directly to IRS Schedule C lines. The <strong>Transaction Detail</strong> tab
            has every individual deductible transaction with merchant, date, amount, and categorization source
            (user-confirmed vs AI-categorized).
        </p>

        <div class="disclaimer">
            <strong>Disclaimer:</strong> This report was generated using AI-assisted categorization.
            Transactions marked "AI" were categorized by machine learning and have not been manually
            verified by the taxpayer. Transactions marked "✓ User" were manually confirmed.
            This report is not tax advice. Please review all categorizations before filing.
            <br><br>
            Generated by <strong>{{ config('app.name') }}</strong> on {{ $summary['generated_at'] }}
        </div>
    </div>
</body>
</html>
