/**
 * InterviewCard — Phase 11-05 INT-02 one-question-at-a-time interview UI.
 *
 * Uses the 11-04 InterviewController endpoints:
 *   POST /api/v1/optimizer/interview/start      — start or resume session
 *   GET  /api/v1/optimizer/interview/{id}/next  — fetch next question
 *   POST /api/v1/optimizer/interview/{id}/questions/{qid}/answer — record answer
 *
 * Controls:
 *   Skip   — advance to next question without recording an answer
 *   Back   — return to previous question (local history)
 *   Resume — implicit via /start (resumes paused session)
 *   Re-answer — answer a previously answered question from history
 *
 * For auto-band findings (INT-07): renders SuggestedConfirmCard.
 * For other bands: renders standard options/free-text input.
 *
 * EDUCATIONAL FRAMING (mandatory per SAFE / owner requirements):
 *   - All question copy uses "may / could / consider" (generated by Claude via the
 *     wording call in InterviewOrchestratorService — this component renders it as-is)
 *   - An inline disclaimer is always visible
 *   - No assertive language in UI chrome
 *
 * DESIGN (D14 / Decision 7 — elevate, don't replace):
 *   sw-* tokens only. Inter type stack. Progress affordance. Spacing rhythm 4px/8px.
 *   Subtle card elevation via shadow-sm. Interaction states on all buttons.
 *   Applied: ui-ux-pro-max Conversion-Optimized pattern — single CTA focus,
 *   progress indicator, focus ring on inputs, minimal distractions per question.
 *   Applied: soft-skill — 16px spacing rhythm, 1.6 line-height for question text,
 *   subtle shadow (shadow-sm) for card depth without heaviness.
 */

import { useState, useCallback, useEffect } from 'react';
import {
  Brain,
  ChevronLeft,
  ChevronRight,
  SkipForward,
  RotateCcw,
  Send,
  Loader2,
  CheckCircle,
  Info,
  AlertCircle,
} from 'lucide-react';
import SuggestedConfirmCard from './SuggestedConfirmCard';
import Badge from './Badge';
import type { InterviewSessionInfo, OptimizationQuestionPayload } from '@/types/spendifiai';
import axios from 'axios';

interface InterviewCardProps {
  /** Tax year for the session (defaults to current year). */
  taxYear?: number;
  /** Called after each successful answer to notify the parent. */
  onAnswered?: (questionId: number, answer: string) => void;
}

type CardState =
  | 'loading-session'
  | 'loading-question'
  | 'question'
  | 'complete'
  | 'error'
  | 'no-questions';

interface HistoryEntry {
  question: OptimizationQuestionPayload;
  answer: string | null;
}

const CURRENT_YEAR = new Date().getFullYear();

export default function InterviewCard({ taxYear = CURRENT_YEAR, onAnswered }: InterviewCardProps) {
  const [cardState, setCardState] = useState<CardState>('loading-session');
  const [session, setSession] = useState<InterviewSessionInfo | null>(null);
  const [currentQuestion, setCurrentQuestion] = useState<OptimizationQuestionPayload | null>(null);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [historyIndex, setHistoryIndex] = useState<number>(-1);
  const [totalAnswered, setTotalAnswered] = useState(0);
  const [freeText, setFreeText] = useState('');
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [showEditMode, setShowEditMode] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  /** Reset per-question input state when question changes. */
  const resetInputState = useCallback(() => {
    setFreeText('');
    setSelectedOption(null);
    setShowEditMode(false);
  }, []);

  /** Start or resume interview session, then fetch the first question. */
  const initSession = useCallback(async () => {
    setCardState('loading-session');
    setErrorMessage(null);
    try {
      const startRes = await axios.post<{ session: InterviewSessionInfo; queue_size: number }>(
        '/api/v1/optimizer/interview/start',
        { tax_year: taxYear }
      );
      const s = startRes.data.session;
      setSession(s);

      if (startRes.data.queue_size === 0) {
        setCardState('no-questions');
        return;
      }

      // Fetch first question
      setCardState('loading-question');
      const nextRes = await axios.get<{
        question: OptimizationQuestionPayload | null;
        session_status: string;
      }>(`/api/v1/optimizer/interview/${s.id}/next`);

      if (!nextRes.data.question) {
        setCardState(nextRes.data.session_status === 'completed' ? 'complete' : 'no-questions');
        return;
      }

      setCurrentQuestion(nextRes.data.question);
      setCardState('question');
      resetInputState();
    } catch {
      setCardState('error');
      setErrorMessage('Could not start the income review. Please try again.');
    }
  }, [taxYear, resetInputState]);

  useEffect(() => {
    initSession();
  }, [initSession]);

  /** Fetch the next question from the session. */
  const fetchNextQuestion = useCallback(async (sessionId: number) => {
    setCardState('loading-question');
    try {
      const res = await axios.get<{
        question: OptimizationQuestionPayload | null;
        session_status: string;
      }>(`/api/v1/optimizer/interview/${sessionId}/next`);

      if (!res.data.question) {
        setCardState(res.data.session_status === 'completed' ? 'complete' : 'no-questions');
        return;
      }

      setCurrentQuestion(res.data.question);
      setCardState('question');
      resetInputState();
    } catch {
      setCardState('error');
      setErrorMessage('Could not load the next question. Please try again.');
    }
  }, [resetInputState]);

  /** Record the user's answer and advance. */
  const handleAnswer = useCallback(async (answer: string) => {
    if (!session || !currentQuestion) return;
    setSubmitting(true);
    try {
      await axios.post(
        `/api/v1/optimizer/interview/${session.id}/questions/${currentQuestion.id}/answer`,
        { answer }
      );

      // Append to local history
      setHistory((prev) => {
        const entry: HistoryEntry = { question: currentQuestion, answer };
        const updated = [...prev, entry];
        setHistoryIndex(updated.length - 1);
        return updated;
      });
      setTotalAnswered((n) => n + 1);
      onAnswered?.(currentQuestion.id, answer);

      await fetchNextQuestion(session.id);
    } catch {
      setErrorMessage('Could not save your answer. Please try again.');
    } finally {
      setSubmitting(false);
    }
  }, [session, currentQuestion, fetchNextQuestion, onAnswered]);

  /** Skip the current question (advance without answering). */
  const handleSkip = useCallback(async () => {
    if (!session || !currentQuestion) return;

    // Track as skipped in history
    setHistory((prev) => {
      const entry: HistoryEntry = { question: currentQuestion, answer: null };
      const updated = [...prev, entry];
      setHistoryIndex(updated.length - 1);
      return updated;
    });

    await fetchNextQuestion(session.id);
  }, [session, currentQuestion, fetchNextQuestion]);

  /** Navigate back to a previously shown question. */
  const handleBack = useCallback(() => {
    if (historyIndex <= 0 || history.length === 0) return;
    const newIndex = historyIndex - 1;
    setHistoryIndex(newIndex);
    const prev = history[newIndex];
    if (prev) {
      setCurrentQuestion(prev.question);
      setCardState('question');
      resetInputState();
    }
  }, [history, historyIndex, resetInputState]);

  /** Re-answer a question from history that was already answered. */
  const handleReAnswer = useCallback(async (answer: string) => {
    if (!session || !currentQuestion) return;
    setSubmitting(true);
    try {
      await axios.post(
        `/api/v1/optimizer/interview/${session.id}/questions/${currentQuestion.id}/answer`,
        { answer }
      );
      // Update history entry
      setHistory((prev) => {
        const updated = [...prev];
        if (historyIndex >= 0 && updated[historyIndex]) {
          updated[historyIndex] = { ...updated[historyIndex], answer };
        }
        return updated;
      });
      onAnswered?.(currentQuestion.id, answer);
      // Advance to next
      await fetchNextQuestion(session.id);
    } catch {
      setErrorMessage('Could not save your answer. Please try again.');
    } finally {
      setSubmitting(false);
    }
  }, [session, currentQuestion, fetchNextQuestion, historyIndex, onAnswered]);

  const isViewingHistory = historyIndex >= 0 && historyIndex < history.length - 1;
  const currentHistoryEntry = history[historyIndex] ?? null;
  const alreadyAnswered = isViewingHistory && currentHistoryEntry?.answer !== null;
  const hasOptions = currentQuestion?.options && currentQuestion.options.length > 0;
  const isAutoSuggest =
    currentQuestion?.band === 'auto' &&
    currentQuestion.suggested_treatment &&
    !showEditMode;

  // ── Render states ────────────────────────────────────────────────────────────

  if (cardState === 'loading-session' || cardState === 'loading-question') {
    return (
      <div className="rounded-2xl border border-sw-border bg-sw-card p-8 flex flex-col items-center gap-3">
        <Loader2 size={22} className="animate-spin text-sw-accent" />
        <p className="text-sm text-sw-muted">
          {cardState === 'loading-session' ? 'Starting your income review...' : 'Loading next question...'}
        </p>
      </div>
    );
  }

  if (cardState === 'error') {
    return (
      <div className="rounded-2xl border border-sw-danger/30 bg-sw-danger/5 p-6 text-center">
        <AlertCircle size={20} className="mx-auto text-sw-danger mb-2" />
        <p className="text-sm text-sw-text mb-3">{errorMessage ?? 'An error occurred.'}</p>
        <button
          onClick={initSession}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-sw-accent text-white text-sm font-semibold hover:bg-sw-accent-hover transition"
        >
          <RotateCcw size={14} /> Retry
        </button>
      </div>
    );
  }

  if (cardState === 'complete') {
    return (
      <div className="rounded-2xl border border-sw-success/30 bg-sw-success-light p-8 text-center">
        <CheckCircle size={32} className="mx-auto text-sw-success mb-3" />
        <h3 className="text-sm font-semibold text-sw-text mb-1">Review complete</h3>
        <p className="text-xs text-sw-muted max-w-xs mx-auto">
          You have answered {totalAnswered} question{totalAnswered !== 1 ? 's' : ''}.
          Your responses may help identify tax opportunities for {taxYear}.
        </p>
        <p className="text-[10px] text-sw-dim mt-3 max-w-xs mx-auto">
          Consider consulting a qualified tax professional before making financial decisions.
        </p>
      </div>
    );
  }

  if (cardState === 'no-questions') {
    return (
      <div className="rounded-2xl border border-sw-border bg-sw-card p-8 text-center">
        <Brain size={28} className="mx-auto text-sw-accent/60 mb-3" />
        <h3 className="text-sm font-semibold text-sw-text mb-1">No questions yet</h3>
        <p className="text-xs text-sw-muted max-w-xs mx-auto">
          Income optimization questions will appear here once your transactions are analyzed.
          Make sure your bank is connected and transactions are categorized.
        </p>
      </div>
    );
  }

  if (!currentQuestion) return null;

  const progressTotal = Math.max(totalAnswered + 1, history.length + 1);

  return (
    <div className="rounded-2xl border border-sw-border bg-sw-card shadow-sm overflow-hidden">
      {/* Progress header */}
      <div className="px-5 py-3 border-b border-sw-border/60 flex items-center justify-between bg-sw-surface/40">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-sw-info-light border border-violet-200 flex items-center justify-center shrink-0">
            <Brain size={13} className="text-sw-info" />
          </div>
          <div>
            <p className="text-[11px] font-semibold text-sw-text-secondary uppercase tracking-wide">
              Income Review
            </p>
            <p className="text-[10px] text-sw-dim">
              Question {totalAnswered + 1} of ~{progressTotal}
            </p>
          </div>
        </div>
        {/* Progress dots */}
        <div className="flex items-center gap-1.5">
          {Array.from({ length: Math.min(progressTotal, 8) }).map((_, i) => (
            <div
              key={i}
              className={`h-1.5 rounded-full transition-all duration-200 ${
                i < totalAnswered
                  ? 'w-3 bg-sw-accent'
                  : i === totalAnswered
                    ? 'w-4 bg-sw-accent/60'
                    : 'w-1.5 bg-sw-border-strong'
              }`}
            />
          ))}
          {progressTotal > 8 && (
            <span className="text-[10px] text-sw-dim ml-1">+{progressTotal - 8}</span>
          )}
        </div>
      </div>

      <div className="p-5 space-y-4">
        {/* Question text */}
        <div className="space-y-2">
          {currentQuestion.band && (
            <Badge
              variant={
                currentQuestion.band === 'auto'
                  ? 'success'
                  : currentQuestion.band === 'conditional'
                    ? 'warning'
                    : 'info'
              }
            >
              {currentQuestion.band === 'auto'
                ? 'High Confidence'
                : currentQuestion.band === 'conditional'
                  ? 'Review Helpful'
                  : 'Specialist'}
            </Badge>
          )}
          <p className="text-[14px] text-sw-text font-medium leading-relaxed">
            {currentQuestion.question}
          </p>
          {alreadyAnswered && currentHistoryEntry?.answer && (
            <p className="text-[11px] text-sw-muted">
              Your previous answer: <span className="font-medium text-sw-text">{currentHistoryEntry.answer}</span>
            </p>
          )}
        </div>

        {/* Answer area */}
        {isAutoSuggest && currentQuestion.suggested_treatment ? (
          <SuggestedConfirmCard
            suggestedTreatment={currentQuestion.suggested_treatment}
            band={currentQuestion.band}
            transactionCount={currentQuestion.transaction_count}
            onConfirm={alreadyAnswered ? handleReAnswer : handleAnswer}
            onEdit={() => setShowEditMode(true)}
            disabled={submitting}
          />
        ) : hasOptions ? (
          <div className="space-y-3">
            <div className="flex flex-wrap gap-2">
              {(currentQuestion.options ?? []).map((opt) => (
                <button
                  key={opt}
                  onClick={() => setSelectedOption(opt)}
                  disabled={submitting}
                  className={`px-3.5 py-2 rounded-lg border text-[13px] font-medium transition ${
                    selectedOption === opt
                      ? 'border-sw-accent bg-sw-accent/10 text-sw-accent'
                      : 'border-sw-border bg-transparent text-sw-muted hover:text-sw-text hover:border-sw-border-strong'
                  } disabled:cursor-not-allowed`}
                >
                  {selectedOption === opt && <span className="inline-block w-3 h-3 mr-1 rounded-full bg-sw-accent" />}
                  {opt}
                </button>
              ))}
            </div>
            <button
              onClick={() => selectedOption && (alreadyAnswered ? handleReAnswer(selectedOption) : handleAnswer(selectedOption))}
              disabled={!selectedOption || submitting}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-sw-accent text-white text-sm font-semibold hover:bg-sw-accent-hover transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {submitting ? <Loader2 size={14} className="animate-spin" /> : <ChevronRight size={14} />}
              {alreadyAnswered ? 'Update answer' : 'Submit'}
            </button>
          </div>
        ) : (
          <div className="space-y-2">
            <div className="flex gap-2">
              <input
                type="text"
                value={freeText}
                onChange={(e) => setFreeText(e.target.value)}
                onKeyDown={(e) =>
                  e.key === 'Enter' && freeText.trim() && !submitting &&
                  (alreadyAnswered ? handleReAnswer(freeText.trim()) : handleAnswer(freeText.trim()))
                }
                placeholder="Type your answer..."
                disabled={submitting}
                className="flex-1 px-3 py-2.5 rounded-lg border border-sw-border bg-sw-bg text-sw-text text-sm placeholder:text-sw-dim focus:outline-none focus:ring-2 focus:ring-sw-accent/30 focus:border-sw-accent transition disabled:opacity-50"
                aria-label="Your answer"
              />
              <button
                onClick={() => freeText.trim() && (alreadyAnswered ? handleReAnswer(freeText.trim()) : handleAnswer(freeText.trim()))}
                disabled={!freeText.trim() || submitting}
                className="px-3 py-2.5 rounded-lg bg-sw-accent text-white text-sm font-semibold hover:bg-sw-accent-hover transition disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {submitting ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
              </button>
            </div>
          </div>
        )}

        {/* Error message */}
        {errorMessage && (
          <p className="text-[11px] text-sw-danger flex items-center gap-1.5">
            <AlertCircle size={12} /> {errorMessage}
          </p>
        )}

        {/* Navigation controls */}
        <div className="flex items-center justify-between pt-1 border-t border-sw-border/60">
          <div className="flex items-center gap-1.5">
            <button
              onClick={handleBack}
              disabled={historyIndex <= 0 || submitting}
              className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg border border-sw-border text-xs text-sw-muted hover:text-sw-text hover:border-sw-border-strong transition disabled:opacity-30 disabled:cursor-not-allowed"
            >
              <ChevronLeft size={13} /> Back
            </button>
            <button
              onClick={handleSkip}
              disabled={submitting || isViewingHistory}
              className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg border border-sw-border text-xs text-sw-muted hover:text-sw-text hover:border-sw-border-strong transition disabled:opacity-30 disabled:cursor-not-allowed"
            >
              <SkipForward size={13} /> Skip
            </button>
          </div>
          <span className="text-[10px] text-sw-dim">
            {totalAnswered > 0 ? `${totalAnswered} answered` : 'No answers yet'}
          </span>
        </div>

        {/* Educational disclaimer */}
        <div className="flex items-start gap-1.5 px-0.5">
          <Info size={11} className="text-sw-dim shrink-0 mt-0.5" />
          <p className="text-[10px] text-sw-dim leading-relaxed">
            Responses may help identify potential tax opportunities. These are not tax advice.
            Please consult a qualified tax professional regarding your specific situation.
          </p>
        </div>
      </div>
    </div>
  );
}
