/**
 * InterviewCard — Phase 11-05 INT-02 one-question-at-a-time interview UI.
 *
 * Uses the 11-04 InterviewController endpoints:
 *   POST /api/v1/optimizer/interview/start      — start or resume session
 *   GET  /api/v1/optimizer/interview/{id}/next  — fetch next question
 *   POST /api/v1/optimizer/interview/{id}/questions/{qid}/answer — record answer
 *
 * Controls:
 *   Skip   — advance to next question without recording an answer
 *   Back   — return to previous question (local history)
 *   Resume — implicit via /start (resumes paused session)
 *   Re-answer — answer a previously answered question from history
 *
 * For auto-band findings (INT-07): renders SuggestedConfirmCard.
 * For other bands: renders standard options/free-text input.
 *
 * EDUCATIONAL FRAMING (mandatory per SAFE / owner requirements):
 *   - All question copy uses "may / could / consider" (generated by Claude via the
 *     wording call in InterviewOrchestratorService — this component renders it as-is)
 *   - An inline disclaimer is always visible
 *   - No assertive language in UI chrome
 *
 * DESIGN (D14 / Decision 7 — elevate, don't replace):
 *   sw-* tokens only. Inter type stack. Progress affordance. Spacing rhythm 4px/8px.
 *   Subtle card elevation via shadow-sm. Interaction states on all buttons.
 *   Applied: ui-ux-pro-max Conversion-Optimized pattern — single CTA focus,
 *   progress indicator, focus ring on inputs, minimal distractions per question.
 *   Applied: soft-skill — 16px spacing rhythm, 1.6 line-height for question text,
 *   subtle shadow (shadow-sm) for card depth without heaviness.
 */

import { useState, useCallback, useEffect } from 'react';
import {
  Brain,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  SkipForward,
  RotateCcw,
  Send,
  Loader2,
  CheckCircle,
  HelpCircle,
  Info,
  AlertCircle,
  Upload,
} from 'lucide-react';
import SuggestedConfirmCard from './SuggestedConfirmCard';
import Badge from './Badge';
import type { InterviewSessionInfo, OptimizationQuestionPayload } from '@/types/spendifiai';
import axios from 'axios';

interface InterviewCardProps {
  /** Tax year for the session (defaults to current year). */
  taxYear?: number;
  /** Called after each successful answer to notify the parent. */
  onAnswered?: (questionId: number, answer: string) => void;
  /**
   * Fix 6: called when the queue drains to empty (queue_size=0 on init OR fetchNextQuestion
   * returns null). Parent uses this to re-fire enqueueGaps and re-mount the card.
   * Without this, the done-for-you loop stalls after the first batch drains.
   */
  onQueueEmpty?: () => void;
  /**
   * Fix 6: remaining facts to show in the "waiting on more questions" state.
   * Derived by parent from objectivesData.objectives[key].blocking.
   * Shown when queue is empty but objectives are still locked.
   */
  remainingFacts?: Array<{ label: string; source: string }>;
}

type CardState =
  | 'loading-session'
  | 'loading-question'
  | 'question'
  | 'complete'
  | 'error'
  | 'no-questions';

interface HistoryEntry {
  question: OptimizationQuestionPayload;
  answer: string | null;
}

const CURRENT_YEAR = new Date().getFullYear();

/** D18 addendum 7 — the escape-hatch choice value (never rendered as text). */
const ESCAPE_VALUE = '__other__';

export default function InterviewCard({ taxYear = CURRENT_YEAR, onAnswered, onQueueEmpty, remainingFacts }: InterviewCardProps) {
  const [cardState, setCardState] = useState<CardState>('loading-session');
  const [session, setSession] = useState<InterviewSessionInfo | null>(null);
  const [currentQuestion, setCurrentQuestion] = useState<OptimizationQuestionPayload | null>(null);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [historyIndex, setHistoryIndex] = useState<number>(-1);
  const [totalAnswered, setTotalAnswered] = useState(0);
  const [freeText, setFreeText] = useState('');
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [selectedMulti, setSelectedMulti] = useState<string[]>([]);
  const [escapeText, setEscapeText] = useState('');
  const [showContext, setShowContext] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [showEditMode, setShowEditMode] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  /**
   * Morning polish Item 1 — derived-value confirm state machine.
   * null / 'confirm' → show the "we estimate $X — does that sound right?" card.
   * 'adjust' → reveal typed input pre-filled with the known value (Higher / Lower path).
   */
  const [derivedConfirmMode, setDerivedConfirmMode] = useState<'confirm' | 'adjust' | null>(null);

  /** Reset per-question input state when question changes. */
  const resetInputState = useCallback(() => {
    setFreeText('');
    setSelectedOption(null);
    setSelectedMulti([]);
    setEscapeText('');
    setShowContext(false);
    setShowEditMode(false);
    setDerivedConfirmMode(null); // Item 1: reset confirm mode on each new question
  }, []);

  /** Start or resume interview session, then fetch the first question. */
  const initSession = useCallback(async () => {
    setCardState('loading-session');
    setErrorMessage(null);
    try {
      const startRes = await axios.post<{ session: InterviewSessionInfo; queue_size: number }>(
        '/api/v1/optimizer/interview/start',
        { tax_year: taxYear }
      );
      const s = startRes.data.session;
      setSession(s);

      if (startRes.data.queue_size === 0) {
        setCardState('no-questions');
        // Fix 6: notify parent so it can re-fire enqueueGaps and re-mount this card
        onQueueEmpty?.();
        return;
      }

      // Fetch first question
      setCardState('loading-question');
      const nextRes = await axios.get<{
        question: OptimizationQuestionPayload | null;
        session_status: string;
      }>(`/api/v1/optimizer/interview/${s.id}/next`);

      if (!nextRes.data.question) {
        const nextState = nextRes.data.session_status === 'completed' ? 'complete' : 'no-questions';
        setCardState(nextState);
        // Fix 6: queue empty on init — notify parent to re-enqueue gaps + re-mount
        onQueueEmpty?.();
        return;
      }

      setCurrentQuestion(nextRes.data.question);
      setCardState('question');
      resetInputState();
    } catch {
      setCardState('error');
      setErrorMessage('Could not start the income review. Please try again.');
    }
  }, [taxYear, resetInputState]);

  useEffect(() => {
    initSession();
  }, [initSession]);

  /** Fetch the next question from the session. */
  const fetchNextQuestion = useCallback(async (sessionId: number) => {
    setCardState('loading-question');
    try {
      const res = await axios.get<{
        question: OptimizationQuestionPayload | null;
        session_status: string;
      }>(`/api/v1/optimizer/interview/${sessionId}/next`);

      if (!res.data.question) {
        const nextState = res.data.session_status === 'completed' ? 'complete' : 'no-questions';
        setCardState(nextState);
        // Fix 6: queue drained after answer — notify parent to re-enqueue gaps + re-mount.
        // Drives the loop: answer → refill → answer → objectives unlock → auto-compute.
        onQueueEmpty?.();
        return;
      }

      setCurrentQuestion(res.data.question);
      setCardState('question');
      resetInputState();
    } catch {
      setCardState('error');
      setErrorMessage('Could not load the next question. Please try again.');
    }
  }, [resetInputState, onQueueEmpty]);

  /** Record the user's answer and advance. */
  const handleAnswer = useCallback(async (answer: string) => {
    if (!session || !currentQuestion) return;
    setSubmitting(true);
    try {
      await axios.post(
        `/api/v1/optimizer/interview/${session.id}/questions/${currentQuestion.id}/answer`,
        { answer }
      );

      // Append to local history
      setHistory((prev) => {
        const entry: HistoryEntry = { question: currentQuestion, answer };
        const updated = [...prev, entry];
        setHistoryIndex(updated.length - 1);
        return updated;
      });
      setTotalAnswered((n) => n + 1);
      onAnswered?.(currentQuestion.id, answer);

      await fetchNextQuestion(session.id);
    } catch {
      setErrorMessage('Could not save your answer. Please try again.');
    } finally {
      setSubmitting(false);
    }
  }, [session, currentQuestion, fetchNextQuestion, onAnswered]);

  /**
   * Skip the current question (advance without answering).
   *
   * DEFECT 2 fix: POST to the durable skip endpoint so the skip is persisted
   * server-side. This prevents the stale-queue self-heal from re-inserting the
   * skipped item at position 1 on reload (the reported "skip just refreshes" loop).
   * The endpoint returns the next question in the same shape as /next.
   */
  const handleSkip = useCallback(async () => {
    if (!session || !currentQuestion) return;

    // Track as skipped in local history (enables Back navigation).
    setHistory((prev) => {
      const entry: HistoryEntry = { question: currentQuestion, answer: null };
      const updated = [...prev, entry];
      setHistoryIndex(updated.length - 1);
      return updated;
    });

    setCardState('loading-question');
    try {
      const res = await axios.post<{
        question: OptimizationQuestionPayload | null;
        session_status: string;
      }>(`/api/v1/optimizer/interview/${session.id}/questions/${currentQuestion.id}/skip`);

      if (!res.data.question) {
        setCardState(res.data.session_status === 'completed' ? 'complete' : 'no-questions');
        return;
      }

      setCurrentQuestion(res.data.question);
      setCardState('question');
      resetInputState();
    } catch {
      setCardState('error');
      setErrorMessage('Could not skip this question. Please try again.');
    }
  }, [session, currentQuestion, resetInputState]);

  /** Navigate back to a previously shown question. */
  const handleBack = useCallback(() => {
    if (historyIndex <= 0 || history.length === 0) return;
    const newIndex = historyIndex - 1;
    setHistoryIndex(newIndex);
    const prev = history[newIndex];
    if (prev) {
      setCurrentQuestion(prev.question);
      setCardState('question');
      resetInputState();
    }
  }, [history, historyIndex, resetInputState]);

  /** Re-answer a question from history that was already answered. */
  const handleReAnswer = useCallback(async (answer: string) => {
    if (!session || !currentQuestion) return;
    setSubmitting(true);
    try {
      await axios.post(
        `/api/v1/optimizer/interview/${session.id}/questions/${currentQuestion.id}/answer`,
        { answer }
      );
      // Update history entry
      setHistory((prev) => {
        const updated = [...prev];
        if (historyIndex >= 0 && updated[historyIndex]) {
          updated[historyIndex] = { ...updated[historyIndex], answer };
        }
        return updated;
      });
      onAnswered?.(currentQuestion.id, answer);
      // Advance to next
      await fetchNextQuestion(session.id);
    } catch {
      setErrorMessage('Could not save your answer. Please try again.');
    } finally {
      setSubmitting(false);
    }
  }, [session, currentQuestion, fetchNextQuestion, historyIndex, onAnswered]);

  const isViewingHistory = historyIndex >= 0 && historyIndex < history.length - 1;
  const currentHistoryEntry = history[historyIndex] ?? null;
  const alreadyAnswered = isViewingHistory && currentHistoryEntry?.answer !== null;
  const hasOptions = currentQuestion?.options && currentQuestion.options.length > 0;
  const isAutoSuggest =
    currentQuestion?.band === 'auto' &&
    currentQuestion.suggested_treatment &&
    !showEditMode;

  // ── D18 template questions: structured choices + escape hatch + context ──
  const templateChoices = currentQuestion?.choices ?? null;
  const noneValue = currentQuestion?.none_value ?? 'none';
  const isMultiSelect =
    currentQuestion?.answer_type === 'multi_select' && !!templateChoices?.length;
  const isChoiceSelect =
    currentQuestion?.answer_type === 'choice' && !!templateChoices?.length;

  // ── Morning polish Item 1: derived-value confirm shape ────────────────────
  // True when the question has a KNOWN/DERIVED value AND is a typed (non-choice) field.
  const isDerivedConfirmActive =
    !!(currentQuestion?.derived_confirm) &&
    (derivedConfirmMode === null || derivedConfirmMode === 'confirm') &&
    !showEditMode;
  const escapeActive =
    (isMultiSelect && selectedMulti.includes(ESCAPE_VALUE)) ||
    (isChoiceSelect && selectedOption === ESCAPE_VALUE);

  /** Toggle a multi-select choice — 'none' and the escape hatch are exclusive. */
  const toggleMultiChoice = useCallback(
    (value: string) => {
      setSelectedMulti((prev) => {
        if (value === noneValue || value === ESCAPE_VALUE) {
          return prev.includes(value) ? [] : [value];
        }
        const withoutExclusive = prev.filter((v) => v !== noneValue && v !== ESCAPE_VALUE);
        return withoutExclusive.includes(value)
          ? withoutExclusive.filter((v) => v !== value)
          : [...withoutExclusive, value];
      });
    },
    [noneValue]
  );

  /** Build the answer string for a template choice/multi-select question. */
  const buildTemplateAnswer = useCallback((): string | null => {
    if (escapeActive) {
      const text = escapeText.trim();
      return text ? `${ESCAPE_VALUE}: ${text}` : null;
    }
    if (isMultiSelect) {
      return selectedMulti.length > 0 ? selectedMulti.join(',') : null;
    }
    return selectedOption;
  }, [escapeActive, escapeText, isMultiSelect, selectedMulti, selectedOption]);

  // ── Render states ────────────────────────────────────────────────────────────

  if (cardState === 'loading-session' || cardState === 'loading-question') {
    return (
      <div className="rounded-2xl border border-sw-border bg-sw-card p-8 flex flex-col items-center gap-3">
        <Loader2 size={22} className="animate-spin text-sw-accent" />
        <p className="text-sm text-sw-muted">
          {cardState === 'loading-session' ? 'Starting your income review...' : 'Loading next question...'}
        </p>
      </div>
    );
  }

  if (cardState === 'error') {
    return (
      <div className="rounded-2xl border border-sw-danger/30 bg-sw-danger/5 p-6 text-center">
        <AlertCircle size={20} className="mx-auto text-sw-danger mb-2" />
        <p className="text-sm text-sw-text mb-3">{errorMessage ?? 'An error occurred.'}</p>
        <button
          onClick={initSession}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-sw-accent text-white text-sm font-semibold hover:bg-sw-accent-hover transition"
        >
          <RotateCcw size={14} /> Retry
        </button>
      </div>
    );
  }

  if (cardState === 'complete') {
    return (
      <div className="rounded-2xl border border-sw-success/30 bg-sw-success-light p-8 text-center">
        <CheckCircle size={32} className="mx-auto text-sw-success mb-3" />
        <h3 className="text-sm font-semibold text-sw-text mb-1">Review complete</h3>
        <p className="text-xs text-sw-muted max-w-xs mx-auto">
          You have answered {totalAnswered} question{totalAnswered !== 1 ? 's' : ''}.
          Your responses may help identify tax opportunities for {taxYear}.
        </p>
        <p className="text-[10px] text-sw-dim mt-3 max-w-xs mx-auto">
          Consider consulting a qualified tax professional before making financial decisions.
        </p>
      </div>
    );
  }

  if (cardState === 'no-questions') {
    // Fix 6: when onQueueEmpty is wired, this state is transient — parent is re-enqueuing
    // and will re-mount this card. Show "Looking for the next batch..." instead of
    // "No questions yet" (which implies a terminal state when objectives are still locked).
    if (onQueueEmpty) {
      return (
        <div className="rounded-2xl border border-sw-border bg-sw-card p-6 text-center">
          <Loader2 size={24} className="mx-auto text-sw-accent/60 mb-3 animate-spin" />
          <h3 className="text-sm font-semibold text-sw-text mb-1">Looking for more questions...</h3>
          {remainingFacts && remainingFacts.length > 0 ? (
            <p className="text-xs text-sw-muted max-w-xs mx-auto leading-relaxed">
              Still working on: {remainingFacts.slice(0, 3).map((f) => f.label).join(', ')}
              {remainingFacts.length > 3 ? ` +${remainingFacts.length - 3} more` : ''}.
            </p>
          ) : (
            <p className="text-xs text-sw-muted max-w-xs mx-auto">
              Preparing the next batch of questions. This only takes a moment.
            </p>
          )}
        </div>
      );
    }

    return (
      <div className="rounded-2xl border border-sw-border bg-sw-card p-8 text-center">
        <Brain size={28} className="mx-auto text-sw-accent/60 mb-3" />
        <h3 className="text-sm font-semibold text-sw-text mb-1">No questions yet</h3>
        <p className="text-xs text-sw-muted max-w-xs mx-auto">
          Income optimization questions will appear here once your transactions are analyzed.
          Make sure your bank is connected and transactions are categorized.
        </p>
      </div>
    );
  }

  if (!currentQuestion) return null;

  const progressTotal = Math.max(totalAnswered + 1, history.length + 1);

  return (
    <div className="rounded-2xl border border-sw-border bg-sw-card shadow-sm overflow-hidden">
      {/* Progress header */}
      <div className="px-5 py-3 border-b border-sw-border/60 flex items-center justify-between bg-sw-surface/40">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-sw-info-light border border-violet-200 flex items-center justify-center shrink-0">
            <Brain size={13} className="text-sw-info" />
          </div>
          <div>
            <p className="text-[11px] font-semibold text-sw-text-secondary uppercase tracking-wide">
              Income Review
            </p>
            <p className="text-[10px] text-sw-dim">
              Question {totalAnswered + 1} of ~{progressTotal}
            </p>
          </div>
        </div>
        {/* Progress dots */}
        <div className="flex items-center gap-1.5">
          {Array.from({ length: Math.min(progressTotal, 8) }).map((_, i) => (
            <div
              key={i}
              className={`h-1.5 rounded-full transition-all duration-200 ${
                i < totalAnswered
                  ? 'w-3 bg-sw-accent'
                  : i === totalAnswered
                    ? 'w-4 bg-sw-accent/60'
                    : 'w-1.5 bg-sw-border-strong'
              }`}
            />
          ))}
          {progressTotal > 8 && (
            <span className="text-[10px] text-sw-dim ml-1">+{progressTotal - 8}</span>
          )}
        </div>
      </div>

      <div className="p-5 space-y-4">
        {/* Question text */}
        <div className="space-y-2">
          {currentQuestion.band && (
            <Badge
              variant={
                currentQuestion.band === 'auto'
                  ? 'success'
                  : currentQuestion.band === 'conditional'
                    ? 'warning'
                    : 'info'
              }
            >
              {currentQuestion.band === 'auto'
                ? 'High Confidence'
                : currentQuestion.band === 'conditional'
                  ? 'Review Helpful'
                  : 'Specialist'}
            </Badge>
          )}
          <p className="text-[14px] text-sw-text font-medium leading-relaxed">
            {currentQuestion.question}
          </p>
          {alreadyAnswered && currentHistoryEntry?.answer && (
            <p className="text-[11px] text-sw-muted">
              Your previous answer: <span className="font-medium text-sw-text">{currentHistoryEntry.answer}</span>
            </p>
          )}

          {/* D18: education lives in a collapsible context, never the body */}
          {currentQuestion.context && (
            <div>
              <button
                onClick={() => setShowContext((v) => !v)}
                className="inline-flex items-center gap-1 text-[11px] font-medium text-sw-muted hover:text-sw-text transition"
                aria-expanded={showContext}
              >
                <HelpCircle size={11} />
                Why we&rsquo;re asking
                <ChevronDown
                  size={11}
                  className={`transition-transform duration-200 ${showContext ? 'rotate-180' : ''}`}
                />
              </button>
              {showContext && (
                <p className="mt-1.5 px-3 py-2.5 rounded-lg bg-sw-surface/70 border border-sw-border/60 text-[11px] text-sw-text-secondary leading-relaxed">
                  {currentQuestion.context}
                </p>
              )}
            </div>
          )}

          {/* D18: doc_affordance — additive upload shortcut when a document could resolve this question */}
          {currentQuestion.doc_affordance && (
            <a
              href="/connect"
              className="inline-flex items-center gap-1.5 text-[11px] font-medium text-sw-accent hover:text-sw-accent-hover transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sw-accent/50 rounded"
            >
              <Upload size={11} />
              {currentQuestion.doc_affordance === 'pay_stub'
                ? 'Upload a pay stub for more precise results'
                : currentQuestion.doc_affordance === 'retirement_statement'
                  ? 'Upload a retirement statement instead'
                  : 'Upload a document instead'}
            </a>
          )}
        </div>

        {/* Answer area */}
        {isDerivedConfirmActive && currentQuestion.prefill_display ? (
          /* Morning polish Item 1: derived-value confirm card */
          <div className="rounded-xl border border-sw-accent/30 bg-sw-accent-light p-4 space-y-3">
            <p className="text-[13px] text-sw-text leading-relaxed">
              {currentQuestion.prefill_approximate
                ? <>Based on your data, we estimate this at about <span className="font-semibold">{currentQuestion.prefill_display}</span>. Does that sound right?</>
                : <>Based on your records, we have this as <span className="font-semibold">{currentQuestion.prefill_display}</span>. Does that sound right?</>
              }
            </p>
            <div className="flex flex-wrap gap-2">
              <button
                onClick={() => (alreadyAnswered ? handleReAnswer : handleAnswer)('confirm')}
                disabled={submitting}
                className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-sw-accent text-white text-sm font-semibold hover:bg-sw-accent-hover transition disabled:opacity-50"
              >
                {submitting ? <Loader2 size={13} className="animate-spin" /> : <Check size={13} />}
                Yes, about right
              </button>
              <button
                onClick={() => {
                  // Pre-fill input with dollar value for money fields; raw otherwise
                  const raw = currentQuestion.prefill_value ?? '';
                  const preFilled = currentQuestion.answer_type === 'money_dollars' && raw
                    ? String(Number(raw) / 100)
                    : raw;
                  setFreeText(preFilled);
                  setDerivedConfirmMode('adjust');
                }}
                disabled={submitting}
                className="px-3.5 py-2 rounded-lg border border-sw-border text-sm text-sw-muted hover:text-sw-text hover:border-sw-border-strong transition disabled:opacity-50"
              >
                Higher
              </button>
              <button
                onClick={() => {
                  const raw = currentQuestion.prefill_value ?? '';
                  const preFilled = currentQuestion.answer_type === 'money_dollars' && raw
                    ? String(Number(raw) / 100)
                    : raw;
                  setFreeText(preFilled);
                  setDerivedConfirmMode('adjust');
                }}
                disabled={submitting}
                className="px-3.5 py-2 rounded-lg border border-sw-border text-sm text-sw-muted hover:text-sw-text hover:border-sw-border-strong transition disabled:opacity-50"
              >
                Lower — let me adjust
              </button>
            </div>
          </div>
        ) : isAutoSuggest && currentQuestion.suggested_treatment ? (
          <SuggestedConfirmCard
            suggestedTreatment={currentQuestion.suggested_treatment}
            questionText={currentQuestion.question}
            band={currentQuestion.band}
            transactionCount={currentQuestion.transaction_count}
            onConfirm={alreadyAnswered ? handleReAnswer : handleAnswer}
            onEdit={() => setShowEditMode(true)}
            disabled={submitting}
          />
        ) : isMultiSelect || isChoiceSelect ? (
          /* D18: structured template choices (single or multi) + escape hatch */
          <div className="space-y-3">
            <div className="space-y-1.5">
              {(templateChoices ?? []).map((choice) => {
                const selected = isMultiSelect
                  ? selectedMulti.includes(choice.value)
                  : selectedOption === choice.value;
                return (
                  <button
                    key={choice.value}
                    onClick={() =>
                      isMultiSelect ? toggleMultiChoice(choice.value) : setSelectedOption(choice.value)
                    }
                    disabled={submitting}
                    className={`w-full flex items-start gap-2.5 px-3.5 py-2.5 rounded-lg border text-left text-[13px] font-medium transition ${
                      selected
                        ? 'border-sw-accent bg-sw-accent/10 text-sw-text'
                        : 'border-sw-border bg-transparent text-sw-muted hover:text-sw-text hover:border-sw-border-strong'
                    } disabled:cursor-not-allowed`}
                  >
                    <span
                      className={`mt-0.5 w-4 h-4 shrink-0 flex items-center justify-center border transition ${
                        isMultiSelect ? 'rounded' : 'rounded-full'
                      } ${selected ? 'border-sw-accent bg-sw-accent text-white' : 'border-sw-border-strong'}`}
                    >
                      {selected && <Check size={11} strokeWidth={3} />}
                    </span>
                    {choice.label}
                  </button>
                );
              })}
            </div>

            {/* Escape hatch free-text ("Something else? Let's talk about it") */}
            {escapeActive && (
              <input
                type="text"
                value={escapeText}
                onChange={(e) => setEscapeText(e.target.value)}
                placeholder="Tell us in your own words..."
                disabled={submitting}
                autoFocus
                className="w-full px-3 py-2.5 rounded-lg border border-sw-border bg-sw-bg text-sw-text text-sm placeholder:text-sw-dim focus:outline-none focus:ring-2 focus:ring-sw-accent/30 focus:border-sw-accent transition disabled:opacity-50"
                aria-label="Describe your situation"
              />
            )}

            <button
              onClick={() => {
                const answer = buildTemplateAnswer();
                if (answer) (alreadyAnswered ? handleReAnswer : handleAnswer)(answer);
              }}
              disabled={!buildTemplateAnswer() || submitting}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-sw-accent text-white text-sm font-semibold hover:bg-sw-accent-hover transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {submitting ? <Loader2 size={14} className="animate-spin" /> : <ChevronRight size={14} />}
              {alreadyAnswered ? 'Update answer' : 'Submit'}
            </button>
          </div>
        ) : hasOptions ? (
          <div className="space-y-3">
            <div className="flex flex-wrap gap-2">
              {(currentQuestion.options ?? []).map((opt) => (
                <button
                  key={opt}
                  onClick={() => setSelectedOption(opt)}
                  disabled={submitting}
                  className={`px-3.5 py-2 rounded-lg border text-[13px] font-medium transition ${
                    selectedOption === opt
                      ? 'border-sw-accent bg-sw-accent/10 text-sw-accent'
                      : 'border-sw-border bg-transparent text-sw-muted hover:text-sw-text hover:border-sw-border-strong'
                  } disabled:cursor-not-allowed`}
                >
                  {selectedOption === opt && <span className="inline-block w-3 h-3 mr-1 rounded-full bg-sw-accent" />}
                  {opt}
                </button>
              ))}
            </div>
            <button
              onClick={() => selectedOption && (alreadyAnswered ? handleReAnswer(selectedOption) : handleAnswer(selectedOption))}
              disabled={!selectedOption || submitting}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-sw-accent text-white text-sm font-semibold hover:bg-sw-accent-hover transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {submitting ? <Loader2 size={14} className="animate-spin" /> : <ChevronRight size={14} />}
              {alreadyAnswered ? 'Update answer' : 'Submit'}
            </button>
          </div>
        ) : (
          <div className="space-y-2">
            <div className="flex gap-2">
              <input
                type="text"
                value={freeText}
                onChange={(e) => setFreeText(e.target.value)}
                onKeyDown={(e) =>
                  e.key === 'Enter' && freeText.trim() && !submitting &&
                  (alreadyAnswered ? handleReAnswer(freeText.trim()) : handleAnswer(freeText.trim()))
                }
                placeholder="Type your answer..."
                disabled={submitting}
                className="flex-1 px-3 py-2.5 rounded-lg border border-sw-border bg-sw-bg text-sw-text text-sm placeholder:text-sw-dim focus:outline-none focus:ring-2 focus:ring-sw-accent/30 focus:border-sw-accent transition disabled:opacity-50"
                aria-label="Your answer"
              />
              <button
                onClick={() => freeText.trim() && (alreadyAnswered ? handleReAnswer(freeText.trim()) : handleAnswer(freeText.trim()))}
                disabled={!freeText.trim() || submitting}
                className="px-3 py-2.5 rounded-lg bg-sw-accent text-white text-sm font-semibold hover:bg-sw-accent-hover transition disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {submitting ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
              </button>
            </div>
          </div>
        )}

        {/* Error message */}
        {errorMessage && (
          <p className="text-[11px] text-sw-danger flex items-center gap-1.5">
            <AlertCircle size={12} /> {errorMessage}
          </p>
        )}

        {/* Navigation controls */}
        <div className="flex items-center justify-between pt-1 border-t border-sw-border/60">
          <div className="flex items-center gap-1.5">
            <button
              onClick={handleBack}
              disabled={historyIndex <= 0 || submitting}
              className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg border border-sw-border text-xs text-sw-muted hover:text-sw-text hover:border-sw-border-strong transition disabled:opacity-30 disabled:cursor-not-allowed"
            >
              <ChevronLeft size={13} /> Back
            </button>
            <button
              onClick={handleSkip}
              disabled={submitting || isViewingHistory}
              className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg border border-sw-border text-xs text-sw-muted hover:text-sw-text hover:border-sw-border-strong transition disabled:opacity-30 disabled:cursor-not-allowed"
            >
              <SkipForward size={13} /> Skip
            </button>
          </div>
          <span className="text-[10px] text-sw-dim">
            {totalAnswered > 0 ? `${totalAnswered} answered` : 'No answers yet'}
          </span>
        </div>

        {/* Educational disclaimer */}
        <div className="flex items-start gap-1.5 px-0.5">
          <Info size={11} className="text-sw-dim shrink-0 mt-0.5" />
          <p className="text-[10px] text-sw-dim leading-relaxed">
            Responses may help identify potential tax opportunities. These are not tax advice.
            Please consult a qualified tax professional regarding your specific situation.
          </p>
        </div>
      </div>
    </div>
  );
}
